name: PermissionsEx
main: ru.tehkode.permissions.bukkit.PermissionsPlugin
version: 100
author: t3hk0d3
website: www.bukkit.org
description: PermissionsEx - permission management plugin. @todo rewrite it.
commands:
  pex:
    description: Provides access to Permissions commands and information.
    usage: |
           Usage:
           /<command> - Display help
           /<command> reload - Reload configuration
           /<command> backend - Print currently using backend
           /<command> backend <backend> - Change permission backend on the fly (Use with caution!)
           /<command> users - Print registred user list (alias)
           /<command> users list - Print registred user list
           /<command> groups - Print registed group list (alias)
           /<command> groups list - Print registred group list
           /<command> user <user> - List all user permissions
           /<command> user <user> list - List all user permissions
           /<command> user <user> group list - List all user groups
           /<command> user <user> add <permission> [world] - Add permission to user
           /<command> user <user> set <permission> <value> [world] - Set permission setting to given value
           /<command> user <user> remove <permission> [world] - Remove permission from user
           /<command> user <user> group add <group> - Add user to specified group
           /<command> user <user> group set <group> - Set only group for user (remove from others)
           /<command> user <user> group remove <group> - Remove user from specified group
           /<command> group <group> - List all group permissions (alias)
           /<command> group <group> list - List all group permissions
           /<command> group <group> user list - List all group user permissions
           /<command> group <group> create [parents] - Create group, optionally set parent groups by comma-separated list
           /<command> group <group> delete - Removes group
           /<command> group <group> parents - List all group parents (alias)
           /<command> group <group> parents list - List all group parents
           /<command> group <group> parents add <parents> - Set parents by comma-separated list
           /<command> group <group> parents remove <parents> - Set parents by comma-separated list
           /<command> group <group> add <permission> [world] - Add permission to group
           /<command> group <group> set <permission> <value> [world] - Add permission for group
           /<command> group <group> remove <permission> [world] - Remove permission from group
           /<command> group <group> user add <users> - Add users (one or comma-separated list) to specified group
           /<command> group <group> user remove <users> - Add users (one or comma-separated list) to specified group
