name: PermissionsEx
main: ru.tehkode.permissions.bukkit.PermissionsEx
version: "${project.version}"
authors: [t3hk0d3, zml2008]
website: http://dev.bukkit.org/server-mods/permissionsex
description: PermissionsEx - Regex-based permission matching for superperms
commands:
  pex:
    description: PermissionsEx commands
    usage: |
           Usage:
           /<command> - Display help
           /<command> reload - Redo all the PermissionsEx injections
           /<command> debug - Toggle debug logging for PEX checks
permissions:
    permissionsex.disable:
        description: Prevents PEX-style matching from taking effect on players
        default: false
    permissionsex.debug:
        description: Allow toggling debug mode on the server
        default: op
    permissionsex.reload:
        description: Allow reinjecting the PEX permissibles
        default: op
