name: Permissions
main: com.nijikokun.bukkit.Permissions.Permissions
version: 100
author: t3hk0d3
website: www.bukkit.org
description: Fork of famous Permissions plugin, permissions framework for bukkit plugins.
commands:
  permissions:
    aliases: [perms, pr]
    description: Provides access to Permissions commands and information.
    usage: |
           Usage:
           /<command> - Display help
           /<command> reload - Reload configuration
           /<command> user <user> - List all user's permissions
           /<command> user <user> list - List all user's permissions
           /<command> user <user> group list - List all user's groups
           /<command> user <user> add <permission> [world] - Add permission for user
           /<command> user <user> set <permission> <value> [world] - Set permission setting to given value
           /<command> user <user> remove <permission> [world] - Remove permission from user
           /<command> user <user> group add <group> - Add user to specified group
           /<command> user <user> group set <group> - Set only group for user
           /<command> user <user> group remove <group> - Remove user from specified group
           /<command> group <group> - List all group's permissions
           /<command> group <group> list - List all group's permissions
           /<command> group <group> user list - List all user's permissions
           /<command> group <group> add <permission> [world] - Add permission for user
           /<command> group <group> set <permission> <value> [world] - Add permission for user
           /<command> group <group> remove <permission> [world] - Add permission for user
           /<command> group <group> user add <users> - Add users (comma separated for more) to specified group
           /<command> group <group> user remove <users> - Add users (comma separated for more) to specified group

